spring.application.name=e-commerce
spring.data.mongodb.uri=mongodb+srv://akshat:akshat123@cluster0.yyiecq8.mongodb.net/Ecommerce?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.database=Ecommerce
server.port=8081