spring.application.name=e-commerce
spring.data.mongodb.uri=${mongo_db}
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.database=Ecommerce
spring.security.oauth.client.registration.google.client-id=${client_id}
spring.security.oauth.client.registration.google.client-secret=${client_secret}
app.google.redirect-uri=#{redirect_uri}
server.port=8081